Rails.application.routes.draw do
  get 'guitars/index'
  get 'guitars/show'
  get 'guitars/new'
  get 'guitars/create'
  post 'guitars/create'
  get 'guitars/edit'
  get 'guitars/update'
  get 'guitars/destroy'
  get 'guitar_collections/index'
  get 'guitar_collections/show'
  get 'guitar_collections/new'
  get 'guitar_collections/create'
  get 'guitar_collections/edit'
  get 'guitar_collections/update'
  get 'guitar_collections/destroy'
  get 'guitar_stores/index'
  get 'guitar_stores/show'
  get 'guitar_stores/new'
  get 'guitar_stores/create'
  get 'guitar_stores/edit'
  get 'guitar_stores/update'
  get 'guitar_stores/destroy'
  get 'guitar_store/index'
  get 'guitar_store/show'
  get 'guitar_store/new'
  get 'guitar_store/create'
  get 'guitar_store/edit'
  get 'guitar_store/update'
  get 'guitar_store/destroy'
  resources :guitars 
  root 'guitars#index'
  mount Guitars::GuitarsAPI => '/api/guitars'  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
